"""initial schema

Revision ID: ba20f91a5597
Revises: 
Create Date: 2026-09-06 15:22:10.909962

"""
from typing import Sequence, Union

import pgvector.sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba20f91a5597'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Extensions must exist before any table uses their types (CITEXT, VECTOR)
    # or their operator classes (gin_trgm_ops, vector_cosine_ops below).
    # pgcrypto: gen_random_uuid() for every UUID primary key.
    op.execute("CREATE EXTENSION IF NOT EXISTS pgcrypto")
    # citext: users.email / candidates.email case-insensitive uniqueness.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # pg_trgm: GIN trigram index powering fuzzy name search on candidates.
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # vector: pgvector, for jd_embedding / profile_embedding + the IVFFlat index.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('credits_balance', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orgs'))
    )
    op.create_table('webhook_idempotency',
    sa.Column('provider_event_id', sa.Text(), nullable=False),
    sa.Column('processed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('provider_event_id', name=op.f('pk_webhook_idempotency'))
    )
    op.create_table('candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('headline', sa.Text(), nullable=True),
    sa.Column('current_title', sa.Text(), nullable=True),
    sa.Column('current_company', sa.Text(), nullable=True),
    sa.Column('location_text', sa.Text(), nullable=True),
    sa.Column('country_code', sa.Text(), nullable=True),
    sa.Column('linkedin_url', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('phone_e164', sa.Text(), nullable=True),
    sa.Column('linkedin_slug', sa.Text(), nullable=True),
    sa.Column('email_hash', sa.Text(), nullable=True),
    sa.Column('name_company_key', sa.Text(), nullable=True),
    sa.Column('profile_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_candidates_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidates')),
    sa.UniqueConstraint('org_id', 'email_hash', name='uq_candidates_org_email_hash'),
    sa.UniqueConstraint('org_id', 'linkedin_slug', name='uq_candidates_org_linkedin_slug')
    )
    op.create_index('ix_candidates_full_name_trgm', 'candidates', ['full_name'], unique=False, postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.create_index('ix_candidates_profile_embedding_ivfflat', 'candidates', ['profile_embedding'], unique=False, postgresql_using='ivfflat', postgresql_ops={'profile_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('recruiter', 'admin')", name=op.f('ck_users_ck_users_role')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_users_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], name=op.f('fk_audit_log_actor_user_id_users')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_audit_log_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_table('candidate_field_sources',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('observed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_field_sources_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_field_sources')),
    sa.UniqueConstraint('candidate_id', 'field_name', 'provider', name='uq_candidate_field_sources_field_provider')
    )
    op.create_table('candidate_provider_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('provider_id', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fetched_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_candidate_provider_records_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_candidate_provider_records')),
    sa.UniqueConstraint('provider', 'provider_id', name='uq_candidate_provider_records_provider_id')
    )
    op.create_index('ix_candidate_provider_records_expires_at', 'candidate_provider_records', ['expires_at'], unique=False)
    op.create_table('consent_records',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('basis', sa.Text(), nullable=False),
    sa.Column('channel', sa.Text(), nullable=True),
    sa.Column('evidence_s3_key', sa.Text(), nullable=True),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("basis IN ('legitimate_interest', 'consent')", name=op.f('ck_consent_records_ck_consent_records_basis')),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_consent_records_candidate_id_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consent_records'))
    )
    op.create_table('searches',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('jd_text', sa.Text(), nullable=False),
    sa.Column('jd_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('spec', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('spec_version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('credits_budget', sa.Integer(), nullable=False),
    sa.Column('credits_spent', sa.Integer(), server_default='0', nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'running', 'complete', 'failed', 'cancelled')", name=op.f('ck_searches_ck_searches_status')),
    sa.CheckConstraint('credits_spent <= credits_budget', name=op.f('ck_searches_ck_searches_credits_within_budget')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_searches_created_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_searches_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_searches'))
    )
    op.create_index('ix_searches_org_created', 'searches', ['org_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('suppression_list',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('identifier_type', sa.Text(), nullable=False),
    sa.Column('identifier_hash', sa.Text(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('source', sa.Text(), nullable=True),
    sa.Column('added_by', sa.UUID(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("identifier_type IN ('phone', 'email', 'linkedin')", name=op.f('ck_suppression_list_ck_suppression_list_identifier_type')),
    sa.CheckConstraint("reason IN ('dnc_registry', 'opt_out', 'manual', 'bounce')", name=op.f('ck_suppression_list_ck_suppression_list_reason')),
    sa.ForeignKeyConstraint(['added_by'], ['users.id'], name=op.f('fk_suppression_list_added_by_users')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_suppression_list_org_id_orgs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_suppression_list')),
    sa.UniqueConstraint('org_id', 'identifier_type', 'identifier_hash', name='uq_suppression_list_org_type_hash')
    )
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('script_template', sa.Text(), nullable=True),
    sa.Column('voice_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('calling_window_start', sa.Time(), nullable=True),
    sa.Column('calling_window_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.Text(), server_default='Asia/Kolkata', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'review', 'ready', 'calling', 'paused', 'complete')", name=op.f('ck_campaigns_ck_campaigns_status')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_campaigns_org_id_orgs')),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], name=op.f('fk_campaigns_search_id_searches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaigns'))
    )
    op.create_table('search_provider_runs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('records_returned', sa.Integer(), nullable=True),
    sa.Column('credits_spent', sa.Integer(), nullable=True),
    sa.Column('request_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("provider IN ('pdl', 'apollo', 'proxycurl', 'coresignal')", name=op.f('ck_search_provider_runs_ck_search_provider_runs_provider')),
    sa.CheckConstraint("status IN ('queued', 'running', 'complete', 'failed', 'rate_limited')", name=op.f('ck_search_provider_runs_ck_search_provider_runs_status')),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], name=op.f('fk_search_provider_runs_search_id_searches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_provider_runs')),
    sa.UniqueConstraint('search_id', 'provider', name='uq_search_provider_runs_search_provider')
    )
    op.create_table('search_results',
    sa.Column('search_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_search_results_candidate_id_candidates'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], name=op.f('fk_search_results_search_id_searches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('search_id', 'candidate_id', name=op.f('pk_search_results'))
    )
    op.create_index('ix_search_results_search_score', 'search_results', ['search_id', sa.literal_column('match_score DESC')], unique=False)
    op.create_table('campaign_candidates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('candidate_id', sa.UUID(), nullable=False),
    sa.Column('stage', sa.Text(), server_default='queued', nullable=False),
    sa.Column('exclusion_reason', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('next_attempt_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('interest_level', sa.Text(), nullable=True),
    sa.Column('disposition_reason', sa.Text(), nullable=True),
    sa.CheckConstraint("exclusion_reason IN ('dnc', 'opted_out', 'region_email_first', 'no_contact')", name=op.f('ck_campaign_candidates_ck_campaign_candidates_exclusion_reason')),
    sa.CheckConstraint("interest_level IN ('high', 'medium', 'low')", name=op.f('ck_campaign_candidates_ck_campaign_candidates_interest_level')),
    sa.CheckConstraint("stage IN ('queued', 'excluded', 'dialing', 'connected', 'qualified', 'not_a_fit', 'interested', 'scheduled', 'unreachable', 'opted_out')", name=op.f('ck_campaign_candidates_ck_campaign_candidates_stage')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_candidates_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], name=op.f('fk_campaign_candidates_candidate_id_candidates')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_candidates'))
    )
    op.create_index('ix_campaign_candidates_campaign_stage', 'campaign_candidates', ['campaign_id', 'stage'], unique=False)
    op.create_index('ix_campaign_candidates_next_attempt_queued', 'campaign_candidates', ['next_attempt_at'], unique=False, postgresql_where=sa.text("stage = 'queued'"))
    op.create_table('campaign_questions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('answer_type', sa.Text(), nullable=False),
    sa.Column('answer_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('required', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint("answer_type IN ('enum', 'number', 'duration', 'money', 'bool', 'text')", name=op.f('ck_campaign_questions_ck_campaign_questions_answer_type')),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_campaign_questions_campaign_id_campaigns'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campaign_questions')),
    sa.UniqueConstraint('campaign_id', 'key', name='uq_campaign_questions_campaign_key'),
    sa.UniqueConstraint('campaign_id', 'position', deferrable=True, initially='DEFERRED', name='uq_campaign_questions_campaign_position')
    )
    op.create_table('credit_ledger',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('search_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('provider', sa.Text(), nullable=True),
    sa.Column('delta_credits', sa.Integer(), nullable=False),
    sa.Column('unit_cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], name=op.f('fk_credit_ledger_campaign_id_campaigns')),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], name=op.f('fk_credit_ledger_org_id_orgs')),
    sa.ForeignKeyConstraint(['search_id'], ['searches.id'], name=op.f('fk_credit_ledger_search_id_searches')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_credit_ledger'))
    )
    op.create_table('call_attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('campaign_candidate_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Text(), server_default='hunar', nullable=False),
    sa.Column('provider_call_id', sa.Text(), nullable=True),
    sa.Column('channel', sa.Text(), server_default='voice', nullable=False),
    sa.Column('to_number_e164', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='queued', nullable=False),
    sa.Column('last_event_seq', sa.BigInteger(), nullable=True),
    sa.Column('duration_secs', sa.Integer(), nullable=True),
    sa.Column('recording_s3_key', sa.Text(), nullable=True),
    sa.Column('transcript_s3_key', sa.Text(), nullable=True),
    sa.Column('cost_micros', sa.BigInteger(), nullable=True),
    sa.Column('consent_recorded', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('ended_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("channel IN ('voice', 'whatsapp', 'sms', 'ivr')", name=op.f('ck_call_attempts_ck_call_attempts_channel')),
    sa.CheckConstraint("status IN ('queued', 'dialing', 'ringing', 'in_progress', 'completed', 'no_answer', 'busy', 'failed', 'rejected')", name=op.f('ck_call_attempts_ck_call_attempts_status')),
    sa.ForeignKeyConstraint(['campaign_candidate_id'], ['campaign_candidates.id'], name=op.f('fk_call_attempts_campaign_candidate_id_campaign_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_attempts')),
    sa.UniqueConstraint('campaign_candidate_id', 'attempt_no', name='uq_call_attempts_candidate_attempt_no'),
    sa.UniqueConstraint('provider_call_id', name=op.f('uq_call_attempts_provider_call_id'))
    )
    op.create_index('ix_call_attempts_active_status', 'call_attempts', ['status'], unique=False, postgresql_where=sa.text("status IN ('queued', 'dialing', 'ringing', 'in_progress')"))
    op.create_table('compliance_checks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('campaign_candidate_id', sa.UUID(), nullable=False),
    sa.Column('check_type', sa.Text(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('checked_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("check_type IN ('dnc', 'opt_out', 'region', 'calling_window')", name=op.f('ck_compliance_checks_ck_compliance_checks_check_type')),
    sa.ForeignKeyConstraint(['campaign_candidate_id'], ['campaign_candidates.id'], name=op.f('fk_compliance_checks_campaign_candidate_id_campaign_candidates'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_compliance_checks'))
    )
    op.create_table('call_answers',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_attempt_id', sa.UUID(), nullable=False),
    sa.Column('question_key', sa.Text(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=True),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('value_number', sa.Numeric(), nullable=True),
    sa.Column('value_bool', sa.Boolean(), nullable=True),
    sa.Column('value_duration_days', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('transcript_offset_ms', sa.Integer(), nullable=True),
    sa.Column('edited_by', sa.UUID(), nullable=True),
    sa.Column('edited_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint('num_nonnulls(value_text, value_number, value_bool, value_duration_days) = 1', name=op.f('ck_call_answers_ck_call_answers_exactly_one_value')),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempts.id'], name=op.f('fk_call_answers_call_attempt_id_call_attempts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], name=op.f('fk_call_answers_edited_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_answers')),
    sa.UniqueConstraint('call_attempt_id', 'question_key', name='uq_call_answers_attempt_question')
    )
    op.create_table('call_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_attempt_id', sa.UUID(), nullable=True),
    sa.Column('provider_event_id', sa.Text(), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('received_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempts.id'], name=op.f('fk_call_events_call_attempt_id_call_attempts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_events')),
    sa.UniqueConstraint('provider_event_id', name=op.f('uq_call_events_provider_event_id'))
    )
    op.create_table('call_transcript_segments',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('call_attempt_id', sa.UUID(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=False),
    sa.Column('end_ms', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.CheckConstraint("speaker IN ('agent', 'candidate')", name=op.f('ck_call_transcript_segments_ck_call_transcript_segments_speaker')),
    sa.ForeignKeyConstraint(['call_attempt_id'], ['call_attempts.id'], name=op.f('fk_call_transcript_segments_call_attempt_id_call_attempts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_call_transcript_segments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call_transcript_segments')
    op.drop_table('call_events')
    op.drop_table('call_answers')
    op.drop_table('compliance_checks')
    op.drop_index('ix_call_attempts_active_status', table_name='call_attempts', postgresql_where=sa.text("status IN ('queued', 'dialing', 'ringing', 'in_progress')"))
    op.drop_table('call_attempts')
    op.drop_table('credit_ledger')
    op.drop_table('campaign_questions')
    op.drop_index('ix_campaign_candidates_next_attempt_queued', table_name='campaign_candidates', postgresql_where=sa.text("stage = 'queued'"))
    op.drop_index('ix_campaign_candidates_campaign_stage', table_name='campaign_candidates')
    op.drop_table('campaign_candidates')
    op.drop_index('ix_search_results_search_score', table_name='search_results')
    op.drop_table('search_results')
    op.drop_table('search_provider_runs')
    op.drop_table('campaigns')
    op.drop_table('suppression_list')
    op.drop_index('ix_searches_org_created', table_name='searches')
    op.drop_table('searches')
    op.drop_table('consent_records')
    op.drop_index('ix_candidate_provider_records_expires_at', table_name='candidate_provider_records')
    op.drop_table('candidate_provider_records')
    op.drop_table('candidate_field_sources')
    op.drop_table('audit_log')
    op.drop_table('users')
    op.drop_index('ix_candidates_profile_embedding_ivfflat', table_name='candidates', postgresql_using='ivfflat', postgresql_ops={'profile_embedding': 'vector_cosine_ops'}, postgresql_with={'lists': 100})
    op.drop_index('ix_candidates_full_name_trgm', table_name='candidates', postgresql_using='gin', postgresql_ops={'full_name': 'gin_trgm_ops'})
    op.drop_table('candidates')
    op.drop_table('webhook_idempotency')
    op.drop_table('orgs')
    # ### end Alembic commands ###
